### ISSUE TITLE
Question about HHKB file

### ISSUE THREAD

**Issue by jakehobbs** [deskcandy/modern-m0110#1]
Hello, sorry to open an issue for this, but I couldn't find any other contact information.

I had the HHKB file cut recently, and it is not lining up properly with the case/PCB. Do you know if anyone has used it with success?

Thanks,
Jake

**Comment by jakehobbs** [comment]
@deskcandy

**Comment by johnheroy** [comment]
Yes this is the original file used to cut plates in the group buy. Make
sure the file is not scaled and cut using the indicated units from the
filename
